apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aiml
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aiml
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 90
